Fix for thermostat operating mode
Cereal2nd/velbus-aio pull request #58
Opened 2022-11-11 07:28 UTC by DannyDeGaspari

Thermostat operating mode not handled correctly. The modes are : disabled, manual, automatic and sleep timer. Whenever the preset is changed (safe, night, day, comfort) the operating mode is forced to go to automatic mode.
This fix retains the operating mode when the preset is changed.

@Cereal2nd, I would also like to add following parameters to be available in home assistant:
- thermostat operating mode (disabled, manual, automatic and sleep timer)
- module program mode (none, winter, summer, holiday)
But the Climate entity does not have such properties, what would be the best way to add these parameters ? Is adding 2 extra channels to the module a good idea ? One for the operating mode and one for the program mode.

2022-11-11 18:24 UTC, Cereal2nd reviewed
Does every module that supports the modulestqtusmessage2 have the sleep timer value?
Same question for the tempsensorstatusmessage. Is this guaranteed to be like this for every received message?

Plus we are trying to improve the testing coverage. Could you write a couple of simple Testcases that implement the changes in this PR?

2022-11-12 14:25 UTC, DannyDeGaspari commented
> Does every module that supports the modulestqtusmessage2 have the sleep timer value?

I'll check for all modules that are listed in this message.

> Same question for the tempsensorstatusmessage.

I did only a bug fix in here and did not add new code or functionality.

> Could you write a couple of simple Testcases that implement the changes in this PR?

I'll try, but I will have to figure out how to do this for this specific message.

2022-11-12 14:37 UTC, Cereal2nd commented
I deed it's only the modulestatusmessage2 that needs checking

For the tests there are some good simple examples in there, the one for the modulename is a good example and is the same idea as this one.

2022-11-13 15:20 UTC, Cereal2nd commented
thanks for adding the testcases, we are almost there.

About the question in hass, i think we should do these things with extra state attributes

2022-11-13 15:21 UTC, Cereal2nd requested changes

2022-11-13 15:21 UTC, Cereal2nd commented on velbusaio/messages/module_status.py
> -register_command(COMMAND_CODE, ModuleStatusMessage2, "VMB1RYS")
These modules, don't they ned this modulemessage?

2022-11-13 15:24 UTC, DannyDeGaspari commented on velbusaio/messages/module_status.py
> -register_command(COMMAND_CODE, ModuleStatusMessage2, "VMB1RYS")
According to the module protocol docs, the command_module_status (0xED) does not exist for these modules.

2022-11-13 15:47 UTC, Cereal2nd commented on velbusaio/messages/module_status.py
> -register_command(COMMAND_CODE, ModuleStatusMessage2, "VMB1RYS")
do you own some of thes emodules?
i checked the docs and it seems to be correct, and i tested it VMB1RYS, but thats the only module i own from that list

2022-11-13 15:55 UTC, DannyDeGaspari commented on velbusaio/messages/module_status.py
> -register_command(COMMAND_CODE, ModuleStatusMessage2, "VMB1RYS")
I only have the VMB4DC from this list. It doesn't respond to module status request.

2022-11-13 15:56 UTC, Cereal2nd approved these changes

2022-11-13 15:56 UTC, merged

2022-11-13 15:56 UTC, Cereal2nd commented
Thanks for the help

2022-11-13 15:57 UTC, DannyDeGaspari commented
> About the question in hass, i think we should do these things with extra state attributes

Does this require changes on the Hass side ? If yes, can you help here or at least guide me into it ?

BTW: during my check on the ModuleStatusMessage I noticed there is still another message variant needed for the VMBGP4PIR module. I own such a module and will implement support for it.

2022-11-13 16:08 UTC, Cereal2nd commented
Yes it requires changes on the Hass side.

So what attributes exactly and how can we get these from the current channel.

If I know this it's easy.

2022-11-13 18:08 UTC, DannyDeGaspari commented
There are 2 attributes:
- "Operating mode": stored in channel._cstatus variable and get from     
`def get_climate_mode(self) -> str:`
No set function defined yet. Should I create it ?
- "Selected program": only decoded in the message itself as a first step, further implementation needed.

2022-11-22 09:02 UTC, DannyDeGaspari commented
@Cereal2nd, Just to let you know that I'm still continuing with further implementations of the VMBGP4PIR module, the thermostat run mode and selected program. But did not had too much spare time past week...